apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: dittnav-eventer-modia
  namespace: personbruker
  labels:
    team: personbruker
spec:
  image: {{version}}
  port: 8080
  liveness:
    path: /dittnav-eventer-modia/internal/isAlive
    initialDelay: 5
  readiness:
    path: /dittnav-eventer-modia/internal/isReady
    initialDelay: 5
  prometheus:
    enabled: true
    path: /dittnav-eventer-modia/internal/metrics
  replicas:
    min: 2
    max: 4
  webproxy: true
  ingresses:
    - "https://dittnav-eventer-modia.nais.adeo.no"
    - "https://app.adeo.no/dittnav-eventer-modia"
vault:
  enabled: true
  paths:
    - kvPath: /kv/prod/fss/dittnav-eventer-modia/personbruker
      mountPath: /var/run/secrets/nais.io/vault
resources:
  limits:
    cpu: "3"
    memory: 768Mi
  requests:
    cpu: "500m"
    memory: 384Mi
