apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: dittnav-eventer-modia
  namespace: {{namespace}}
  labels:
    team: personbruker
spec:
  image: {{version}}
  port: 8080
  liveness:
    path: /dittnav-eventer-modia/internal/isAlive
    initialDelay: 5
  readiness:
    path: /dittnav-eventer-modia/internal/isReady
    initialDelay: 5
  prometheus:
    enabled: true
    path: /dittnav-eventer-modia/internal/metrics
  replicas:
    min: 2
    max: 4
  webproxy: true
  ingresses:
{{#each ingresses}}
  - "{{this}}"
{{/each}}
  vault:
    enabled: true
    paths:
      - kvPath: /kv/{{cluster}}/fss/dittnav-eventer-modia/{{namespace}}
        mountPath: /var/run/secrets/nais.io/vault
  resources:
    limits:
      cpu: "3"
      memory: 768Mi
    requests:
      cpu: "500m"
      memory: 384Mi
