name: Bygg branch

on:
  push:
    branches-ignore:
      - master
      - main

jobs:
  build-branch:
    runs-on: ubuntu-latest
    steps:

      - name: Sjekk ut koden
        uses: actions/checkout@v3

      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17.x'
          cache: 'gradle'

      - name: Bygg prosjekt og kjør tester
        uses: navikt/pb-common-gh-actions/build@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}